# Generated by Django 4.2.4 on 2023-08-23 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demandante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('coDemandante', models.CharField(max_length=255)),
                ('coDemandantePai', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'demandante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DodfPublicacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('coMateria', models.CharField(max_length=255)),
                ('coDemandante', models.CharField(max_length=255)),
                ('secao', models.CharField(max_length=10)),
                ('titulo', models.CharField(max_length=255)),
                ('preambulo', models.TextField()),
                ('tipo', models.CharField(max_length=255)),
                ('situacao', models.CharField(max_length=255)),
                ('regraSituacao', models.CharField(max_length=255)),
                ('layout', models.CharField(max_length=255)),
                ('nuOrdem', models.CharField(max_length=255)),
                ('texto', models.TextField()),
                ('carga', models.DateTimeField()),
            ],
            options={
                'db_table': 'dodfPublicacao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Jurisdicionada',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('coDemandante', models.CharField(max_length=255)),
                ('sigla', models.CharField(max_length=20)),
                ('apelido', models.CharField(max_length=50)),
                ('vl_bens_serv', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vl_obras_eng', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'db_table': 'jurisdicionada',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('sigla', models.CharField(max_length=3)),
                ('titular', models.CharField(max_length=80)),
                ('email', models.CharField(max_length=80)),
                ('ramal', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'unidade',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PublicacaoAnalisada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dodf', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mpc.dodfpublicacao')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.userprofile')),
            ],
            options={
                'db_table': 'publicacao_analisada',
            },
        ),
    ]
