# Generated by Django 4.2.4 on 2023-08-22 15:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mpc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacaoanalisada',
            name='carga',
        ),
        migrations.RemoveField(
            model_name='publicacaoanalisada',
            name='coDemandante',
        ),
        migrations.RemoveField(
            model_name='publicacaoanalisada',
            name='coMateria',
        ),
        migrations.RemoveField(
            model_name='publicacaoanalisada',
            name='dodf_id',
        ),
        migrations.RemoveField(
            model_name='publicacaoanalisada',
            name='preambulo',
        ),
        migrations.RemoveField(
            model_name='publicacaoanalisada',
            name='secao',
        ),
        migrations.RemoveField(
            model_name='publicacaoanalisada',
            name='texto',
        ),
        migrations.RemoveField(
            model_name='publicacaoanalisada',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='publicacaoanalisada',
            name='titulo',
        ),
        migrations.AddField(
            model_name='publicacaoanalisada',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicacaoanalisada',
            name='dodf',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mpc.dodfpublicacao'),
        ),
        migrations.AddField(
            model_name='publicacaoanalisada',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
